= Neo4j Procedure Template
:branch: 5.x
:root: https://github.com/mslouma88/neo4j-procedure-template/{branch}/src

This project is an example you can use to build user defined procedures, functions and aggregation functions in Neo4j.
It contains two procedures, for reading and updating a full-text index.

To try this out, simply clone this repository and have a look at the source and test code (including Test-Server-Setup).

[Note]
This project requires a Neo4j {branch}.x dependency.


== User Defined Procedure

The user defined procedure allows you to get the incoming and outgoing relationships for a given node.

See link:{root}/main/java/project/GetRelationshipTypes.java[`GetRelationshipTypes.java`] and the link:{root}/test/java/project/GetRelationshipTypesTests.java[`GetRelationshipTypesTests.java`].

[source,cypher]
----
MATCH (n:Person)
CALL project.getRelationshipTypes(n)
YIELD outgoing, incoming
RETURN outgoing, incoming;
----


== User Defined Aggregation Function

The aggregation function `project.last` returns the last row of an aggregation.

[source,cypher]
----
MATCH (n:Person)
WITH n ORDER BY n.born
WITH project.last(n) as last
RETURN last
----

See link:{root}/main/java/project/Last.java[`Last.java`] and the link:{root}/test/java/project/LastTest.java[`LastTest.java`].

== Building

This project uses maven, to build a jar-file with the procedure in this
project, simply package the project with maven:

    mvn clean package

This will produce a jar-file,`target/procedure-template-project-salam-et-nesrine-1.0.0-SNAPSHOT.jar`,
that can be deployed in the `plugin` directory of your Neo4j instance.

== License

Apache License V2, see LICENSE
